### ISSUE TITLE
Password is exposed.

### ISSUE THREAD

**Issue by kiyolol** [timbcodes/old-portfolio#1]
A little while ago I was browsing, and I found this repo. Your `Gmail` password is exposed in [/routes/index.js#L21](https://github.com/timbcodes/old-portfolio/blob/main/routes/index.js#L21)

Would recommend changing it or getting rid of the code that stores it.

**Comment by timbcodes** [comment]
Oh, wow! Good find. I was being lazy when I built this and didn't use a .env file and totally forgot about it when I made this public. Thanks a bunch!!

**Comment by kiyolol** [comment]
No problem! Just make sure you start using a .env file!!
